#!/bin/bash

# Identify the home of our gtkrc file, important for setting styles of
# gtk-based applications
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# enable for hidpi displays
export GDK_SCALE=1

setxkbmap -option 'ctrl:nocaps'

# set keyboard rate
xset r rate 160 80

sudo timedatectl set-timezone Europe/Berlin
# sudo timedatectl set-timezone America/New_York
# sudo timedatectl set-timezone America/Los_Angeles

# Ensure Zoom output volume stays constant
/home/dan/scripts/fuck_zoom.sh 100 &

# Clipboard manager (used with rofi)
greenclip daemon &

# Start espanso
# espanso restart  # broken in Ubuntu 22

# set trackball rate
# xinput --set-prop "Primax Kensington Eagle Trackball" "Device Accel Constant Deceleration" 3 || true

# eye breaks
# safeeyes &

# Wallpaper
feh --bg-fill --no-xinerama --randomize ~/Media/images/wallpaper/*
# xsetroot -solid black

# Config in ~/.config/redshift/redshift.conf
redshift &

picom -b

# Now, finally, start xmonad
exec xmonad
